name: Keep-Alive Ping

on:
  schedule:
    - cron: '*/12 * * * *' # alle 12 Minuten

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Webhook
        run: curl -s https://weeztix-automation.onrender.com/weeztix
